before_install:
  - sudo apt-get install -y python-software-properties python g++ make -y
  - sudo add-apt-repository ppa:chris-lea/node.js -y
  - sudo apt-get update
  - sudo apt-get install nodejs -y
  - sudo npm install -g bower -y
  - sudo npm install -g gulp -y
  - sudo npm install -g npm@2
install:
  sudo npm install
script:
  gulp release
after_success:
  ./tools/compress.sh
